module.exports  = [
  {
    title: 'Shopping cart',
    program_type: 'React / Redux-thunk',
    image_link: 'https://s3.amazonaws.com/photo-links/web21.png',
    web_link: 'http://shopping-cart-client.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/shopping-cart.git',
  },
  {
    title: 'Moviedb Search',
    program_type: 'React / Redux',
    image_link: 'https://s3.amazonaws.com/photo-links/web19.png',
    web_link: 'http://moviedb-thunk-project.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/movieDB-thunk.git',
  },
  {
    title: 'Carousel',
    program_type: 'React / Redux-thunk',
    image_link: 'https://s3.amazonaws.com/photo-links/web22.png',
    web_link: 'http://carousel-redux.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/redux-carousel.git',
  },
  {
    title: 'Reverse geolocator',
    program_type: 'React / Redux-saga',
    image_link: 'https://s3.amazonaws.com/photo-links/web20.png',
    web_link: 'http://reverse-geolocator.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/geolocator-redux-saga.git',
  },
  {
    title: 'Life-coach website',
    program_type: 'React / Redux',
    image_link: 'https://s3.amazonaws.com/photo-links/web1.png',
    web_link: 'http://svetlana-phsychology.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/svetlana-psy',
  },
  {
    title: 'Iceland Tours Prototype',
    program_type: 'React / Redux',
    image_link: 'https://s3.amazonaws.com/photo-links/web2.png',
    web_link: 'http://iceland-ring-road-redux.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/iceland-ringroad-react',
  },
  {
    title: 'Intrepid search',
    program_type: 'React / Yelp API',
    image_link: 'https://s3.amazonaws.com/photo-links/web3.png',
    web_link: 'http://react-intrepid-search.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/Raven',
  },
  {
    title: 'Youtube search',
    program_type: 'Angular 4 / Youtube API',
    image_link: 'https://s3.amazonaws.com/photo-links/web4.png',
    web_link: 'http://angular-youtube-search.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/youtube-angular-search-with-service',
  },
  {
    title: 'Jewelry store prototype',
    program_type: 'React',
    image_link: 'https://s3.amazonaws.com/photo-links/web5.png',
    web_link: 'http://igor-jeweler.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/igor-jewelry',
  },
  {
    title: 'Dashboard prototype',
    program_type: 'Angular 5',
    image_link: 'https://s3.amazonaws.com/photo-links/web6.png',
    web_link: 'http://project-dashboard-angular2.s3-website-us-east-1.amazonaws.com/',
    git_link: 'hhttps://github.com/mawglih/project_dashboard_angular2',
  },
  {
    title: 'Teacher website and store',
    program_type: 'Wordpress / PHP / CSS / HTML',
    image_link: 'https://s3.amazonaws.com/photo-links/web7.png',
    web_link: 'https://vikaraskina.com/',
    git_link: null,
  },
  {
    title: 'Doctor\'s website',
    program_type: 'AngularJS',
    image_link: 'https://s3.amazonaws.com/photo-links/web8.png',
    web_link: 'http://start-fresh-life.org/',
    git_link: 'https://github.com/mawglih/doctor3',
  },
  {
    title: 'Marine Upholstery store website',
    program_type: 'AngularJS / PHP',
    image_link: 'https://s3.amazonaws.com/photo-links/web9.png',
    web_link: 'http://alphamarineupholstery.com/',
    git_link: 'https://github.com/mawglih/taran',
  },
  {
    title: 'Spotify',
    program_type: 'React',
    image_link: 'https://s3.amazonaws.com/photo-links/web10.png',
    web_link: 'http://react-spotify.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/jamming_react',
  },
  {
    title: 'Youtube search',
    program_type: 'React / Youtube API',
    image_link: 'https://s3.amazonaws.com/photo-links/web11.png',
    web_link: 'http://react-youtube-search.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/youtube-react-search',
  },
  {
    title: 'Movie search',
    program_type: 'VueJS / Movie API',
    image_link: 'https://s3.amazonaws.com/photo-links/web12.png',
    web_link: 'http://vue-cinema-project.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/Vue-uni/tree/master/vue-cinema',
  },
  {
    title: 'Imgur Store',
    program_type: 'VueJS / Imgur API',
    image_link: 'https://s3.amazonaws.com/photo-links/web13.png',
    web_link: 'http://vue-imgur-poster-bus.s3-website.us-east-2.amazonaws.com/',
    git_link: 'https://github.com/mawglih/Vue-uni/tree/master/vue-poster-store',
  },
  {
    title: 'Youtube search',
    program_type: 'VueJS / Youtube API',
    image_link: 'https://s3.amazonaws.com/photo-links/web14.png',
    web_link: 'http://vue-youtube-search.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/youtube-vue-search',
  },
  {
    title: 'Weather search',
    program_type: 'React / Redux / Weather API',
    image_link: 'https://s3.amazonaws.com/photo-links/web15.png',
    web_link: 'http://weather-react.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/weather-react-redux',
  },
  {
    title: 'Hotel B&B Prototype',
    program_type: 'React / Firebase',
    image_link: 'https://s3.amazonaws.com/photo-links/web16.png',
    web_link: 'http://hotel--bb-react-firebase.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/hotel-bb-react',
  },
  {
    title: 'BookStore Prototype',
    program_type: 'React / Redux',
    image_link: 'https://s3.amazonaws.com/photo-links/web17.png',
    web_link: 'http://bookstore-react.s3-website-us-east-1.amazonaws.com/',
    git_link: 'https://github.com/mawglih/bookstore-react',
  },
  {
    title: 'Bilingual Children Prototype',
    program_type: 'React / Redux',
    image_link: 'https://s3.amazonaws.com/photo-links/web18.png',
    web_link: 'http://vikaraskina-react.s3-website-us-east-1.amazonaws.com',
    git_link: 'https://github.com/mawglih/vikaraskina-react',
  },
]
